export const MyJourneyData = [
  {
    year: '2023',
    organization: 'Frontdreams Technologies',
    link: 'https://frontdreams.com',
    position: 'Web Designer',
    duration: 'Sep 2022 - Present',
    experiences: [
      'Design and develop visually appealing, responsive, and user-friendly websites for clients, ensuring alignment with client brand and/or business objectives and adhering to industry standards',
    ],
  },
  {
    year: '2023',
    organization: 'Progressive Animal Welfare Services (PAWS)',
    link: 'https://pawscanada.ca/',
    position: 'eCommerce Specialist',
    duration: 'Apr 2023 - Present',
    experiences: [
      'Pioneer and oversee full-scale e-commerce, from vendor selection to successful market entry, while selecting suitable platforms and technologies for sales',
      'Improve the digital experience by leveraging Google Analytics reports to analyze user behavior, identify areas for improvement, and make data-driven decisions that enhance website performance and increase conversion rates',
    ],
  },
  {
    year: '2022',
    organization: 'Go Together Travel Agency',
    link: 'https://gotogether-s.vercel.app/',
    position: 'Front End Developer',
    duration: 'Sep 2022 - Feb 2023',
    experiences: [
      'Created a large-scale mobile web application for a travel agency, reduced the page load time, improved the rendering speed from 21 seconds to 10 seconds, and transformed a non-responsive website into a responsive one',
      'Developed a secure login mechanism using modern authentication techniques such as JWT, and created user features for sign-up, login, and my account, leading to increased user engagement and platform growth',
      'Built a survey page, enabling users to navigate and identify desired tour packages more efficiently, resulting in a reduction in customer searching time and improving overall business satisfaction ratings',
      'Implemented server-side rendering (SSR) techniques to significantly enhance the rendering speed of product lists and product detail pages that contained big data, resulting in improved performance and user experience',
      'Collaborated with UI/UX designers to contribute to improving the product, analyzing the technical risks, and translating prototype mockups into clean, efficient and reusable code while adhering to best practices',
      'Integrated data from internal APIs developed by the back-end team, utilizing technologies including the React-based framework Next.js, TypeScript, Redux Toolkit, HTML5, CSS3, Scss/Sass, and MUI to develop a feature-rich website',
    ],
  },
  {
    year: '2022',
    organization: 'Fast Campus',
    link: 'https://fastcampus.co.kr/',
    position: 'Certificate, Front End Developer',
    duration: 'Mar 2022 - Oct 2022',
    experiences: [
      'Completed a one-year certificate program at Fast Campus, a private education academy in Korea',
      'CAcquired proficiency in the following technologies: JavaScript ES6, TypeScript, Vue.js, React.js (React Hooks, Redux), SASS/SCSS, Bootstrap, and Python',
      'Gained extensive knowledge in Git, GitHub, SPA(Single-Page Applications), RESTful APIs, ESLint, Webpack, and Responsive Design',
      'Successfully completed two personal projects and contributed to three team projects. For a detailed overview of my projects',
    ],
  },
  {
    year: '2021',
    organization: 'Digital Main Street',
    link: 'https://digitalmainstreet.ca/',
    position: 'Web Designer',
    duration: 'Jun 2021 - Jul 2021',
    experiences: [
      'Worked at an agency which assists main street businesses to adopt digital technologies to increase online sales',
      'Established e-commerce websites with WordPress, Wix, and Shopify for clients including pumpkin farm, jewelry seller, and gym as a part of Ontario Digital Transformation Grant Program ran by the state government',
      'Provided SEO audit and development, website operation training, and guidelines on how to manage the website to the clients',
    ],
  },
  {
    year: '2019',
    organization: 'advertience Inc.',
    link: 'https://advertience.com/',
    position: 'Web Developer',
    duration: 'Feb 2019 - Jan 2021',
    experiences: [
      'Communicated effectively with clients to collect and analyze business requirements, developing and maintaining mobile-friendly websites optimized for accessibility, scalability and speed within a digital marketing agency',
      'Achieved a 15% increase in website traffic and a 5% increase in customer purchases for the pharmaceutical company Drysol by developing a landing page with SEO principles and Google Ads A/B testing',
      "Led the full web development cycle for Coastal Rides' mobile-responsive website, resulting in a remarkable 10% increase in app downloads and successfully meeting the company's quarterly marketing objectives",
      'Collaborated with a marketing team to implement marketing strategies and created email campaigns, website content, landing pages, event tracking, and marketing materials, and conducted SEO audits and development',
      "Provided insights and recommendations to improve clients' online performance by monitoring Google Analytics, implementing Google Tag Manager tracking codes, and optimizing website visibility in search results with Google Search Console",
      'Created high-quality code based on prototype designs, utilizing HTML5, CSS3, JavaScript ES6, Bootstrap, and WordPress to develop responsive websites that are compatible with all devices and modern browsers',
    ],
  },
  {
    year: '2019',
    organization: 'Temerity Analytics Inc.',
    link: 'https://temerityanalytics.com/',
    position: 'UX/UI Designer',
    duration: 'Feb 2019 - Jan 2021',
    experiences: [
      'Engaged in cross-functional collaboration, partnering with software developers, marketing teams, and other business units to analyze requirements and develop UI solutions for Merln, a marketing analytics software',
      'Played a key role in maintaining design consistency by creating 20 design guidelines for a development team, aligning them with the design direction and implementing UI/UX enhancements for a development team',
      'Created UI design prototypes with Adobe XD, incorporating various components and pages such as messenger, FSA map, chat box, sentiment analysis, and admin page, to drive intuitive and engaging user experiences',
    ],
  },
  {
    year: '2017',
    organization: 'Humber College',
    link: 'https://mediaarts.humber.ca/programs/media-communications.html',
    position: 'Diploma, Media Communications',
    duration: 'Sep 2017 - Apr 2019',
    experiences: [
      'Acquired a wide range of skills including digital marketing, content creation, photography, videography, graphic design, and web design',
    ],
  },
]
