export const MyJourneyData = [
  {
    year: '2024',
    organization: 'ChargeLab',
    link: 'https://chargelab.co/',
    position: 'Hardware Integration Engineer',
    duration: 'Sep 2024 - Present',
    experiences: [
      "Test EV chargers and firmware integration with ChargeLab's software.",
      'Verify Level 2 and Level 3 chargers for deployment.',
      'Execute hardware automation tests and analyze results.',
      'Design and develop UIs for a testing automation tool to streamline OEM use.',
      'Enhance charger performance through troubleshooting and issue resolution.',
      'Coordinate firmware updates with manufacturers for the North American market.',
    ],
  },
  {
    year: '2023',
    organization: 'Frontdreams Technologies',
    link: 'https://frontdreams.com',
    position: 'Web Designer',
    duration: 'Sep 2023 - Aug 2023',
    experiences: [
      'Designed, developed, and launched 5+ client websites.',
      'Trained 20+ interns in WordPress development and project management.',
      'Created responsive and visually appealing websites using HTML, CSS, and JavaScript.',
    ],
  },
  {
    year: '2022',
    organization: 'Go Together Travel Agency',
    link: 'https://gotogether-s.vercel.app/',
    position: 'Front End Developer',
    duration: 'Sep 2022 - Feb 2023',
    experiences: [
      'Created a large-scale mobile web app, developing 5 features and 13 pages.',
      'Implemented secure login with JWT and user features like signup and account management.',
      'Built a survey page recommending vacation packages based on user preferences.',
      'Enhanced page performance with server-side rendering (SSR).',
      'Collaborated with UI/UX designers to translate mockups into clean, reusable code.',
      'Integrated backend data using RESTful APIs, Next.js, TypeScript, Redux Toolkit, HTML, CSS, and MUI.',
    ],
  },
  {
    year: '2022',
    organization: 'Fast Campus',
    link: 'https://fastcampus.co.kr/',
    position: 'Certificate, Front End Developer',
    duration: 'Mar 2022 - Oct 2022',
    experiences: [
      'Gained proficiency in JavaScript ES6, TypeScript, React.js, Vue.js and Python.',
      'Acquired knowledge in Git, GitHub, SPA, RESTful APIs, ESLint and Webpack.',
      'Completed two personal projects and contributed to three team projects.',
    ],
  },
  {
    year: '2021',
    organization: 'Digital Main Street',
    link: 'https://digitalmainstreet.ca/',
    position: 'Web Designer',
    duration: 'Jun 2021 - Jul 2021',
    experiences: [
      'Established e-commerce websites using WordPress, Wix, and Shopify.',
      'Developed sites for diverse clients, including a pumpkin farm, jewelry seller, and gym.',
      'Provided SEO audits and website operation training.',
    ],
  },
  {
    year: '2019',
    organization: 'advertience Inc.',
    link: 'https://advertience.com/',
    position: 'Web Developer',
    duration: 'Feb 2019 - Jan 2021',
    experiences: [
      'Translated mockups into responsive, high-quality websites using HTML5, CSS3, JavaScript ES6, Bootstrap, and WordPress.',
      "Increased Drysol's traffic and purchases through SEO and A/B testing.",
      "Boosted Coastal Rides' app downloads through web development.",
      'Improved site visibility using Google Analytics and Google Tag Manager.',
      'Implemented marketing strategies and conducted SEO audits.',
    ],
  },
  {
    year: '2019',
    organization: 'Temerity Analytics Inc.',
    link: 'https://temerityanalytics.com/',
    position: 'UX/UI Designer',
    duration: 'Feb 2019 - Jan 2021',
    experiences: [
      'Developed intuitive UI solutions for Merln, an advanced analytics platform.',
      'Analyzed requirements and translated them into functional UI designs.',
      'Created 20 design guidelines to ensure consistency and ease of implementation.',
      'Designed and prototyped UI components using Adobe XD.',
    ],
  },
  {
    year: '2017',
    organization: 'Humber College',
    link: 'https://mediaarts.humber.ca/programs/media-communications.html',
    position: 'Diploma, Media Communications',
    duration: 'Sep 2017 - Apr 2019',
    experiences: [
      'Designed and developed websites using HTML, CSS, and web design tools.',
      'Learned strategic media writing, social media marketing, and digital content creation.',
      'Created and edited multimedia content, including videos and graphics.',
      'Utilized software like Photoshop, InDesign, XD, After Effects, Illustrator, and Premiere Pro.',
    ],
  },
]
