export const MyJourneyData = [
  {
    year: '2024',
    organization: 'ChargeLab',
    link: 'https://chargelab.co/',
    position: 'Hardware Integration Engineer',
    duration: 'Sep 2024 - Present',
    experiences: [
      'Led QA testing for EV chargers to meet OCPP 1.6/2.0.1, CTEP, and Plug and Charge standards',
      'Built Python/Django/JavaScript automation web tool, cutting QA testing time from 4 weeks to 1 day',
      'Reduced session failures by 30% by adding timeout logic and analyzing charger data',
      'Developed a self-serve tool with clear UX, boosting capacity from 40 to unlimited units',
      'Diagnosed field issues by reviewing OCPP logs and charger-backend behavior',
    ],
  },
  {
    year: '2023',
    organization: 'Frontdreams Technologies',
    link: 'https://frontdreams.com',
    position: 'Web Designer',
    duration: 'Sep 2023 - Aug 2023',
    experiences: [
      'Designed, developed, and launched 5+ client websites.',
      'Trained 20+ interns in WordPress development and project management.',
      'Created responsive and visually appealing websites using HTML, CSS, and JavaScript.',
    ],
  },
  {
    year: '2022',
    organization: 'Go Together Travel Agency',
    link: 'https://gotogether-s.vercel.app/',
    position: 'Front End Developer',
    duration: 'Sep 2022 - Feb 2023',
    experiences: [
      'Built JWT auth for login, signup, and account management to protect user data',
      'Created search and booking features with Next.js and REST APIs for fast results',
      'Built Product Detail Page with Redux and SSR for speed and dynamic data handling',
      'Built a survey page recommending vacation packages based on user preferences.',
      'Coded responsive UI from designs using HTML, CSS, MUI, and JavaScript',
    ],
  },
  {
    year: '2022',
    organization: 'Fast Campus',
    link: 'https://fastcampus.co.kr/',
    position: 'Certificate, Front End Developer',
    duration: 'Mar 2022 - Oct 2022',
    experiences: [
      'Gained proficiency in JavaScript ES6, TypeScript, React.js, Vue.js and Python.',
      'Acquired knowledge in Git, GitHub, SPA, RESTful APIs, ESLint and Webpack.',
      'Completed two personal projects and contributed to three team projects.',
    ],
  },
  {
    year: '2021',
    organization: 'Digital Main Street',
    link: 'https://digitalmainstreet.ca/',
    position: 'Web Designer',
    duration: 'Jun 2021 - Jul 2021',
    experiences: [
      'Established e-commerce websites using WordPress, Wix, and Shopify.',
      'Developed sites for diverse clients, including a pumpkin farm, jewelry seller, and gym.',
      'Provided SEO audits and website operation training.',
    ],
  },
  {
    year: '2019',
    organization: 'advertience Inc.',
    link: 'https://advertience.com/',
    position: 'Web Developer',
    duration: 'Feb 2019 - Jan 2021',
    experiences: [
      'Built responsive sites from prototypes using HTML, CSS, JS, Bootstrap, and WordPress',
      'Performed cross-browser testing and fixes for Chrome, Firefox, and Safari',
      'Created SEO landing page that boosted sales for a pharmaceutical client',
      'Delivered full web build that increased app downloads for a ride-hailing client',
      'Improved site visibility using Google Analytics and Google Tag Manager.',
    ],
  },
  {
    year: '2019',
    organization: 'Temerity Analytics Inc.',
    link: 'https://temerityanalytics.com/',
    position: 'UX/UI Designer',
    duration: 'Feb 2019 - Jan 2021',
    experiences: [
      'Developed intuitive UI solutions for Merln, an advanced analytics platform.',
      'Analyzed requirements and translated them into functional UI designs.',
      'Created 20 design guidelines to ensure consistency and ease of implementation.',
      'Designed and prototyped UI components using Adobe XD.',
    ],
  },
  {
    year: '2017',
    organization: 'Humber College',
    link: 'https://mediaarts.humber.ca/programs/media-communications.html',
    position: 'Diploma, Media Communications',
    duration: 'Sep 2017 - Apr 2019',
    experiences: [
      'Designed and developed websites using HTML, CSS, and web design tools.',
      'Learned strategic media writing, social media marketing, and digital content creation.',
      'Created and edited multimedia content, including videos and graphics.',
      'Utilized software like Photoshop, InDesign, XD, After Effects, Illustrator, and Premiere Pro.',
    ],
  },
]
